application: compagnie-aorte
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# - url: /favicon\.ico
#   static_files: favicon.ico
#   upload: favicon\.ico
- url: /css
  static_dir: src/css
- url: /img
  static_dir: src/img
- url: /js
  static_dir: src/js
- url: /json
  static_dir: src/json
- url: /lib
  static_dir: src/lib
- url: /mp3
  static_dir: src/mp3
- url: /spectacles
  static_dir: src/spectacles
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
